import type { CategoryItem } from "./types";

const silence = { src: "/audio/placeholder/silence.wav" };

export const alphabetItems: CategoryItem[] = [
  {
    id: "cat",
    name: "Cat",
    letter: "C",
    category: "animals",
    image: { src: "/images/generated/animal-cat.png", alt: "A cartoon cat" },
    audio: silence,
    tiers: ["preschool", "earlyElementary"],
    free: true,
  },
  {
    id: "dog",
    name: "Dog",
    letter: "D",
    category: "animals",
    image: { src: "/images/placeholder/animal-dog.svg", alt: "A cartoon dog" },
    audio: silence,
    tiers: ["preschool", "earlyElementary"],
  },
  {
    id: "fish",
    name: "Fish",
    letter: "F",
    category: "animals",
    image: { src: "/images/placeholder/animal-fish.svg", alt: "A cartoon fish" },
    audio: silence,
    tiers: ["preschool", "earlyElementary"],
  },
  {
    id: "apple",
    name: "Apple",
    letter: "A",
    category: "fruits",
    image: { src: "/images/generated/fruit-apple.png", alt: "A red apple" },
    audio: silence,
    tiers: ["preschool", "earlyElementary"],
    free: true,
  },
  {
    id: "banana",
    name: "Banana",
    letter: "B",
    category: "fruits",
    image: { src: "/images/placeholder/fruit-banana.svg", alt: "A yellow banana" },
    audio: silence,
    tiers: ["preschool", "earlyElementary"],
  },
  {
    id: "grapes",
    name: "Grapes",
    letter: "G",
    category: "fruits",
    image: { src: "/images/placeholder/fruit-grapes.svg", alt: "A bunch of grapes" },
    audio: silence,
    tiers: ["preschool", "earlyElementary"],
  },
  {
    id: "red",
    name: "Red",
    letter: "R",
    category: "colors",
    image: { src: "/images/placeholder/color-red.svg", alt: "The color red" },
    audio: silence,
    tiers: ["preschool"],
  },
  {
    id: "blue",
    name: "Blue",
    letter: "B",
    category: "colors",
    image: { src: "/images/placeholder/color-blue.svg", alt: "The color blue" },
    audio: silence,
    tiers: ["preschool"],
  },
  {
    id: "yellow",
    name: "Yellow",
    letter: "Y",
    category: "colors",
    image: { src: "/images/placeholder/color-yellow.svg", alt: "The color yellow" },
    audio: silence,
    tiers: ["preschool"],
  },
];
